# Generated by Django 5.0.14 on 2025-10-06 11:54

import django.core.validators
import django.db.models.deletion
import fleet.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('model', models.CharField(choices=[('LIGHTWEIGHT', 'Lightweight'), ('MIDDLEWEIGHT', 'Middleweight'), ('CRUISERWEIGHT', 'Cruiserweight'), ('HEAVYWEIGHT', 'Heavyweight')], max_length=20)),
                ('weight_limit', models.PositiveIntegerField(help_text='grams, max 500', validators=[django.core.validators.MaxValueValidator(500)])),
                ('battery_capacity', models.PositiveIntegerField(help_text='percentage 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('state', models.CharField(choices=[('IDLE', 'Idle'), ('LOADING', 'Loading'), ('LOADED', 'Loaded'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered'), ('RETURNING', 'Returning')], default='IDLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, validators=[fleet.validators.validate_medication_name])),
                ('weight', models.PositiveIntegerField(help_text='grams')),
                ('code', models.CharField(max_length=100, unique=True, validators=[fleet.validators.validate_medication_code])),
                ('image', models.ImageField(upload_to='medications/')),
            ],
        ),
        migrations.CreateModel(
            name='CargoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_items', to='fleet.drone')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_items', to='fleet.medication')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cargoitem',
            constraint=models.UniqueConstraint(fields=('drone', 'medication'), name='unique_drone_medication'),
        ),
    ]
